@startuml
'https://plantuml.com/sequence-diagram

autonumber

Alice -> B: registry
B --> Alice: return client_id & client_secret
Alice -> A: Alice access
A --> B: request authentication code
B --> Alice: redirect login page
Alice -> B: login and approve
B --> A: redirect A & return authentication code
A --> B: request token
B --> A: return token
A --> B: request user info
B --> A:

@enduml