@startuml
'https://plantuml.com/sequence-diagram

autonumber

用户 -> 第三方应用: 用户访问第三方应用
第三方应用 --> 认证服务器: 请求授权码
认证服务器 --> 用户: 重定向到授权页面
用户 -> 认证服务器: 登录并授权
认证服务器 --> 第三方应用: 颁发授权码
第三方应用 --> 认证服务器: 用授权码申请token
认证服务器 --> 第三方应用: 颁发token
第三方应用 --> 资源服务器: 获取用户数据
资源服务器 --> 认证服务器: 获取token
认证服务器 --> 资源服务器: 发送token
资源服务器 --> 资源服务器: 验证token
资源服务器 --> 第三方应用: 发送用户数据

@enduml